- .gitignore
- backend/routes/groupRoutes.js
- leffasovellus/package-lock.json
- leffasovellus/src/components/content/Comingsoon.css
- leffasovellus/src/components/content/Comingsoon.js
- package-lock.json
> Lisätty componentti comingsoon ja endpointit groupRoutes.js

- frontend/src/components/header/Header.jsx
- frontend/src/css/styles.css
- Nyt tän jälkeen yritän aloittaa sit sitä kirjautumishärveliä
> Kapeampi headeri ja "maitokahvi" värit

- backend/auth/authModel.js
- backend/auth/authRoutes.js
- backend/auth/authService.js
- backend/movie/movieService.js
- frontend/src/components/content/homepage/Comingsoon.css
- frontend/src/components/content/homepage/Home.jsx
- frontend/src/components/content/homepage/Popularmovies.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/components/header/Header.jsx
- frontend/src/css/styles.css
- Backend Movies: korjailua elokuvahaun osalta.
- Frontin tyylittely: toggleDivs (kirjautumisikkuna ja hamppari-ikkuna) erivärinen pohja teemoilla light ja dark.
- Suosituimmat elokuvat etusivulle Comingsoonin alle.
- MovieDetails -komponenttia päivitetty, nyt teeman mukaan taustaväri infolle ja arvosteluille, backdrop-kuva coverina taustalle yms.
Light:
Dark:
MovieDetails (dark theme):
> #15 #40 #44: suosituimmat etusivulle ja vähän ikkunoiden säätöä

- backend/auth/authRoutes.js
- backend/server.js
- frontend/src/App.jsx
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/content/user/user.css
- frontend/src/components/header/Header.jsx
- frontend/src/components/header/Login.jsx
- frontend/src/css/styles.css
- Muutin auth/routesia pari riviä 
- /auth/ mukaan polkuihin
- logout 
- Fronttiin headerin säätöä kirjautumisen alustamiseksi
- Hakee kannasta käyttäjän ja pääsee ns. "oman tilin" sivulle
- Visuaalisena muutoksena: navipalkin ja hampparin käyttäytyminen, kun käyttäjä on kirjautunut vs. kun ei ole
kts. kuvat
Dark teemalla: 
Light teema
> #13: Login -pohjaa

- frontend/src/components/content/homepage/Home.css
- frontend/src/components/content/homepage/Home.jsx
- frontend/src/components/content/homepage/Rightsidebar.css
- frontend/src/components/content/homepage/Rightsidebar.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/styles.css
- Pientä, pientä sen footerin kanssa yms. Yritellään vielä lisää toki
> Testataan mm. footeria

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- backend/routes/profileRoutes.js
- frontend/src/App.jsx
- frontend/src/components/content/user/GroupList.jsx
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/content/user/user.css
- postgredump/skeema-testidatalla.sql
- Voidaan katsoa profiilisivuja, kun tiedetään profiilinimi osoitteessa:
```http://localhost:5173/profile/NIMI```
- Profiilisivuilla geneerisiä koirakuvia 💯 voisi melkein luulla koirasivustoksi 👍 
- Käyttäjän nimi, descriptioni ja käyttäjän ryhmät tulee
- **Paljon** vielä kesken, mutta yo. osat toimii
- Pikkasen tähän liittyviä lisäyksiä myös backendissä osissa Profile ja Group
- Skeema testidatalla updateineen mukana
**Sneak peek**
> #50: Profiilin tietoja kannasta (backend + frontend)

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/App.jsx
- frontend/src/components/content/user/GroupList.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/content/user/user.css
- Käyttäjän sivupohjaa polkuun ```src/components/content/user/ProfileDetails.jsx```
- Lisätty muutamia tyylimäärityksiä tähän sivupohjaan polkuun ```src/components/content/user/user.css```
- Reititystä profiiliin App.jsx kautta
- Lisätty groupServiceen ja groupRoutesiin osa, missä haetaan kannasta ryhmän nimi jäsenen id:n perusteella
- Profiili-pohjaan kovakoodattuu _ryhmälista käyttäjälle 1_
> #50 #32: ProfileDetails ja ryhmähakua jäsenen perusteella bäkkiin

- frontend/src/App.jsx
- frontend/src/components/content/homepage/Rightsidebar.css
- frontend/src/components/content/homepage/Rightsidebar.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/components/header/Header.jsx
- frontend/src/css/media.css
- frontend/src/css/styles.css
- Kuvat kertokoot
- Otsikkotaso ainakin ok
- Sisältöä pitää vähän seurailla ja sovittaa mukaan sitten
- Toteutus jatkuu siis myöhemmin
> #48: Responsiivisuutta

- backend/movie/movieModel.js
- backend/movie/movieRoutes.js
- backend/movie/movieService.js
- frontend/src/App.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/group/GroupSettings.jsx
- frontend/src/components/content/group/MemberList.jsx
- frontend/src/components/content/group/group.css
- frontend/src/components/content/homepage/Comingsoon.css
- frontend/src/components/content/homepage/Comingsoon.jsx
- frontend/src/components/content/homepage/Home.css
- frontend/src/components/content/homepage/Home.jsx
- frontend/src/components/content/homepage/Popularmovies.css
- frontend/src/components/content/homepage/Rightsidebar.css
- frontend/src/components/content/homepage/Rightsidebar.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/styles.css
++ Poistin myös error elementin app.jsx kun sitä ei ollut mukana, lisätkää takaisin kun error komponentti pushataan.
Näyttää missä katsottavissa Suomessa ja ohjaa tmdb sivulle josta voi vuokrata tai tilata palvelun
Lisätty leffan nimi ja yhteenveto kun vie hiiren posterin päälle hakukentässä, sidottu sivunvaihto alas ja lisätty nuolet.
Lisätty näytöksiin selaus ees ja taas 10 kerrallaan.
Tehty vielä turhanpäiväiset sivut ryhmänäkymälle, jos noilla haluaa heittää vesilintua, se sopii
+muita css viilauksia jotta reeleissä leffan titteli näkyy oikein. Lisätty myös koppi katsottavissa elementtiin leffan sivulle jos axios data on väärän muotoista. Tällöin elementti ei lataa mutta sivu ei kaadu.
> Leffahakuun ja leffasivuun liittyviä muutoksia yms.

- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/movies/movies.css
**Tässä pr:ssä:**
- maksimimerkkimäärä overview-kuvaukselle 
- sekä transitio-korjauksia leffahakuun
> Movie search

- backend/auth/authModel.js
- backend/auth/authRoutes.js
- backend/auth/authService.js
- backend/middleware/auth.js
- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
Tokenin luomisessa siihen upotetaan nyt username ja profileid. 
Voit tunnistaa jatkossa käyttäjän tokenin mukaan käyttämällä endpointissa "auth" middlewarea ja sen jälkeen hakea profileid tiedon res.locals.profileid muuttujasta. 
Voit käyttää auth middlewarea, kun otat sen käyttöön koodin alussa "const { auth } = require('../middleware/auth');" rivillä.
> Tokenin luomisessa siihen upotetaan nyt myös profileid

- frontend/src/components/content/homepage/Home.css
- frontend/src/components/content/homepage/Home.jsx
- frontend/src/components/content/homepage/Homepage.css
- frontend/src/components/content/homepage/Latestreviews.jsx
- frontend/src/css/media.css
- frontend/src/css/theme.css
**Tässä pr:ssä etusivulla näkyviin arvosteluihin liittyen**
- mariginia laatikoihin
- hoveria teemoittain💚
- kuvan sijoittelu taulukon osan yläreunaan
- responsiivisuutta korjattu niiltä osin, kun oli rikki
> #24: Homepage reviews 

- frontend/src/css/media.css
Tuohon on jossain conflict mergen yhteydessä karannut hassuja, tässä ok versio.
> Media.css fix

- frontend/src/App.jsx
> #62: login - logout - localstorage

- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/user/ReviewList.jsx
- frontend/src/css/emoji.css
- frontend/src/css/styles.css
- frontend/src/css/theme.css
**Tässä pr:ssä** 
- Arvostelujen poisto ja muokkaaminen onnistuu profiilin kautta
- Poistossa tuplavarmistus eli kysyy vahvistusta
- Muokkaamisessakin "peruutus"mahdollisuus
- Tein lisää endpointteja reviewiin, mitä tarvitsin 
**Jatkokehitykseen vielä profiilin osilta**
- Hieman parannettavaa näissä arvostelutoiminnoissa
- Sivutukset kaikkeen
- Suosikkilista ja sen hallinnointi
- Ryhmälinkitykset listaukseen
Pitäkääs kivaa
> #87: Arvostelujen muokkaus ja poisto profiilista

- frontend/src/App.jsx
- frontend/src/ThemeProvider.jsx
- frontend/src/components/header/Header.jsx
- Hampparista voi nyt vaihtaa teemaa
- Teema local storageen
> #40: Teeman vaihto mahdolliseksi hamppariin + teema localstr

- frontend/src/components/content/community/AllGroups.jsx
- frontend/src/components/content/community/UserList.jsx
- frontend/src/components/content/community/community.css
- frontend/src/css/media.css
- frontend/src/css/styles.css
- postgredump/skeema-testidatalla.sql
- community -sivulle ulkonäkömuutosta (asettelu)
- ja mobiilissa menee allekain
> Community page

- frontend/src/App.jsx
Nyt uloskirjautuminen ohjaa etusivulle, niin ei jää hassuja näkymiä
> logout ohjaa etusivulle

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/App.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/ReviewForm.jsx
- frontend/src/css/styles.css
- postgredump/skeema-testidatalla.sql
- kiiruhtakaas tekemään arvosteluita 
- seuraavaks laitan myös sarjoille tän toimii, nyt toimii vasta leffoilla
> #131: arvostelun lähettäminen (Elokuvat!) käyttöliittymästä

- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/App.jsx
- frontend/src/components/content/community/AllReviews.jsx
- frontend/src/components/content/community/Community.jsx
- frontend/src/components/content/community/community.css
- Arvostelut tulee nyt yhteisöt sivun alaosaan 
- Siitä puuttuu seuraavat:
- arvostelujen hakeminen
- arvostelijan nimimerkki ja linkitys
> #85: arvostelut listana yhteisön alaosaan

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/App.jsx
- frontend/src/components/content/community/AllReviews.jsx
- frontend/src/components/content/community/community.css
- frontend/src/components/content/movies/ReviewFormSerie.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- Sarjoihin pystyy laittamaan arvosteluja leffojen ohella
- Yhteisö välilehden arvostelut-osiota
> #85 #131: arvosteluja sarjoihin ja community -välilehteä

- backend/group/groupService.js
- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/components/content/user/GroupList.jsx
- pieni muutos endpointtiin ja lisätty linkitys profiilin kautta haettaviin ryhmiin 
- unohdin vaihtaa branchia, niin tuli tähän samaan pr:ään myös hieman ehostusta leffa- ja sarjahakuun 
- nyt voi selata leffoja ja sarjoja eri kiekosta
- jatkokehityksessä voiskohan rullat laittaa sivuille?
> #87: ryhmälinkki profiilista

- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/Forum.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/homepage/Rightsidebar.jsx
- frontend/src/components/content/user/GroupList.jsx
Puuttuu vielä että näkymä vaihtelee onko kirjautunut vai ei.
muokattu vähän endpointteja, korjattu linkitys näytösajoista leffasivulle ja tehty näemmä päällekkäinen korjaus profiilista ryhmäsivulle.
> Foorumitoiminnot

- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
- backend/profile/profileService.js
- frontend/src/components/content/user/MyAccount.jsx
Kirjautuneen käyttäjän tilin hallinnalliset toiminnot: Poista tili, vaihda käyttäjätunnusta ja sähköpostia ja muuta profiilin yksityisyyttä. 
Tilin poistamisen yhteydessä ei vielä mahdollista jättää arvosteluja anonyymin käyttäjän nimelle.
> #82 Kirjautuneen käyttäjän tilin hallinnalliset toiminnot

- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/Forum.jsx
Viestinlisäyslaatikko ei näy enää jos ei ole ryhmän jäsen
> Foorumitoiminnot, nyt vain jäsen voi laittaa viestiä

- backend/auth/authModel.js
- backend/auth/authRoutes.js
- backend/auth/authService.js
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/content/user/user.css
Kirjautuneen käyttäjän salasanan vaihtaminen kokonaan valmis. Uusi endpointti (auth/password) luotu auth kansioon ja frontissa tsekataan salasanojen täsmäävyys, jotta salasana voidaan vaihtaa.
> #135 Kirjautuneen käyttäjän salasanan vaihtaminen

- backend/auth/authModel.js
Tein vaan ihan yhen rivin muutoksen salasanan palauttamista sähköpostiin tekevään koodiin. Vetäkää suoraan mainiin vaan.
> Update email service configuration in authModel.js

- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/Reviews.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
> muutettu SeriesDetails ja MovieDetails näyttämään oikeat arvostelut

- backend/favoritelist/favoritelistRoutes.js
- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- backend/movie/movieRoutes.js
- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
- backend/profile/profileService.js
- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- Backend jutut jäsennelty
- businesslogiikka Serviceissä
- kantakyselyt Modeleissa
- reitit Routeseissa
- Suurin osa endpointeista oli onneksi käytössä, mutta esimerkiksi groupsin kohdalla en löytänyt useampaa
- nämä puuttuvat vaikuttivat siltä, että ovat ilmeisesti tulosssa, tarkentakaa mahdollisesti asiaa vielä
> #165: Backendia (endpoints) järjestelty, melkein kaikki käytössä mitä tähän asti tehty

- backend/group/groupModel.js
- frontend/src/css/media.css
- nyt näkyy taas groupin kuvaus ja kuvake
> #165: bugfix: groupin tiedot näkyy nyt

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/content/user/ProfileEdit.jsx
- puuttui osia  getReviewsByItem:istä
- ja hieman profile-editin puolta fix
> #167 #165 : pari puuttuvaa asiaa paikalleen

- frontend/src/components/content/homepage/Rightsidebar.jsx
- frontend/src/components/content/movies/ExistingReview.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/movies/SliceSearch.jsx
- Korjattu rightsidebar-virhe:
- lisätty key={index + 1} rv 177, nyt toimii
- Vähennetty ilmoituksia konsoliin silloin kun providers ei löydy leffalle tai sarjalle
> Puuttuvat providers >> virheviestien vähentämistä ja rightsidebard key

- postgredump/Leffaysi-tietokanta-skeema.sql
- sql/database.sql
> Puuttuva osa: grouppicurl

- frontend/src/components/content/group/GroupDetails.jsx
> siirretty liittymisnapin paikkaa

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/GroupList.jsx
Muutettu niin että profiilissa ei näy ryhmät joiden jäsen käyttäjä ei vielä ole vaan jotka odottavat hyväksyntää.
> Ryhmät profiilissa

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/GroupList.jsx
> Poistu ryhmästä

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/group/MemberList.jsx
- frontend/src/components/content/user/GroupList.jsx
> Jäsenen poistaminen ryhmästä

- frontend/src/components/content/group/Forum.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/group/group.css
- Sijoitin chatin omalle ikkunalleen alapuolelle, jos vaikka suosikkilistaus tulis edelliselle paikalle?
- Näytti ihan kivaselta erikokosilla näytöillä
> Group ja Forum -tyylittelyy

- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
- backend/profile/profileService.js
- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/user/MyAccount.jsx
Käyttäjä voi nyt valita poistaessaan tiliänsä, että poistaa kaikki tietonsa tai voi jättää arvostelut anonyymin käyttäjän alle.
> #86 reviews to anon

- frontend/src/components/content/movies/Carousel.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/media.css
- frontend/src/css/styles.css
Tein tähän pr:ään leffa- ja sarjasivujen muotoilua, jossa:
- korjasin responsiivisuuden, nyt pitäs näyttää kivalta myös mobiilissa
- providerit sijoittelin infon alle pois taulusta
> #44: leffasarjasivujen respo korjattu ja providers

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/MemberList.jsx
> lisätty pyyntöjen ja kutsujen käsittely ryhmän jäsenluetteloon

- frontend/src/components/content/community/AllGroups.jsx
- frontend/src/components/content/community/AllReviews.jsx
- frontend/src/components/content/community/UserList.jsx
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/css/styles.css
- postgredump/Leffaysi-testidataa.sql
- postgredump/Leffaysi-tietokanta-skeema.sql
- Testidataa hieman oikaistu suoremmaksi
- Alertviestit asetettu näkymään tilinhallinta-sivulla laatikoidensa yhteyteen + timeoutti sellaisiin, mitkä heittää ulos tai kun tili poistetaan (jotta käyttäjä ehtii lukemaan viestin)
- Hieman tyylittelyä, linkkejä, otsikoita, buttoneita aseteltu
- Yhteisö-sivun ryhmä- ja jäsenmäärät näyttävät nyt vakiota eikä heilu haun mukaan.
> Fontit ja linkit

- backend/favoritelist/favoritelistRoutes.js
- backend/favoritelist/favoritelistService.js
- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/GroupEdit.jsx
Poistaa myös jäsenlistan ja favoritelistan ryhmältä
> lisätty ryhmänpoisto ryhmän muokkaukseen. 

- frontend/src/components/content/user/user.css
- frontend/src/components/header/Login.jsx
- frontend/src/css/styles.css
- Alertteja ja timeoutteja myös login ikkunaan ja sivulle
> alertteja myös loginiin

- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/group/MemberList.jsx
> memberlistaan kruunu mainusereille

- backend/group/groupModel.js
- backend/group/groupRoutes.js
- backend/group/groupService.js
- frontend/src/components/content/group/MemberList.jsx
> memberlististä voi nyt promotee ja demotee.

- frontend/src/components/content/group/MemberList.jsx
> lisätty jäsenlistaan lataus

- frontend/src/App.jsx
- frontend/src/components/header/Header.jsx
Tätäpä ei kuvalla oikein havainnollista
> Loginikkuna dropdownikkuna sulkeutuu kun painaa ohi

- frontend/src/components/content/group/MemberList.jsx
> jäsenhallinnasta ei voi enää alentaa tai poistaa itseään

- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/footer/Footer.jsx
- frontend/src/css/styles.css
- Laitoin loadingit sivujen ProfileDetails ja GroupDetails -runkoihin kiinni siten, että sisältöä ei yritetä näyttää ennenkuin se on ladannut ja tarkastanut ryhmässä ryhmän tiedot ja profiilissa profiilin tiedot. Näin mm. yksityisyydet pysyvät suojassa.
> #50 #68: Sivulle tultaessa lataa sivun ennen sisällön näyttämistä

- frontend/src/components/content/homepage/Homepage.css
- frontend/src/components/content/homepage/Latestreviews.jsx
- otsikosta pääsee myös infosivulle 
- hoverit yms
> #224 : Homepage -linkityksiä

- .gitignore
- backend/profile/profileModel.js
- frontend/src/components/content/community/AllGroups.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/header/Header.jsx
- frontend/src/components/header/Login.jsx
- robot/client.robot
- robot/variables.py
- Robottia tehdessä törmäsin haasteeseen, missä ei poistanutkaan ns. "tyhjiä ryhmiä" eli ei poistanut jäsentä ryhmästä, jossa hän oli ainoana käyttäjänä ja ryhmät jäivät leijumaan
- Tähän korjaus profileModelissa, jossa nyt transaktiolla ensin poistetaan jäsen ryhmistä, joissa on, sitten poistetaan tyhjäksi jääneet ryhmät (joissa ei ole jäseniä) ja viimeisenä poistetaan tili
- Toimii hienosti manuaalisesti ja myös automatisoidusti robotilla
- Frontin jutuksiin lisätty id-tunnisteita, joita pitkin robotti navigoi
- Robotin ajaminen on aika hauskaa, **kokeilkaa!** 😄 
- Tässä lyhyesti gpt:n avustaman ohjeet sen asentamiseksi:
**Sitten kun oot edelliset vaiheet tehnyt, niin voit suorittaa tän pr:n mukana tulevan robotin juuritason kansiosta robot**
**Huomaathan, että sulla pitää olla yhteydet …
> #143: tilinpoisto update ja robottia client toimintoja

- backend/auth/authRoutes.js
- backend/auth/authService.js
- backend/middleware/auth.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/App.jsx
- frontend/src/components/auth/authSignal.js
- frontend/src/components/content/community/AdminDeleteReview.jsx
- frontend/src/components/content/community/AllReviews.jsx
- frontend/src/components/content/community/Community.jsx
- frontend/src/components/content/community/GroupCarousel.jsx
- frontend/src/components/header/Login.jsx
- postgredump/Leffaysi-tietokanta-skeema.sql
- sql/database.sql
- Kantamuutos, jossa profileen tulee usertype, defaulttina user ja pitää olla joko user tai admin
-  Admin toiminnallisuus lisätty
- Nyt admin pystyy poistamaan arvosteluja yhteisö-sivun kautta
Jatkokehitykseen esim. että admin näkee kaikkien ryhmien sisällön? 
Kaikkien käyttäjien profiilit?
Pystyy hallinnoimaan jotain muuta, mitä?
> #139: Admin-toiminnallisuus aloitettu ja lisätty arvostelujen poistoon yhteisö-sivulla

- env-example
.env tiedoston malli lisätty koko arkiston juureen, mihin oikea .env tiedostokin tulee sijoittaa.
// Backend
PORT = your-backend-port // port where the backend is running, eg. 3001
TMDB_API_KEY = 'you-api-key' // get your own TMDB API key from https://www.themoviedb.org/
JWT_SECRET = 'your-secret' // for example 'abc123'
EMAIL_SERVICE = 'your-email-service' // for example 'gmail'
EMAIL_USER = 'your-email@mail.com'
EMAIL_PASS = 'your email password'
// Database
DB_USER = 'your-database-user'
DB_HOST = 'your-database-host'
DB_DATABASE = 'your-database-name'
DB_PASSWORD = 'your-database-password'
DB_PORT = your-database-port // for example 5432
DB_SSL = true // if you are using ssl
// Frontend
VITE_APP_BACKEND_URL = 'backend-url' // url where the backend is running
> #164 env-tiedoston malli lisätty

- frontend/src/components/content/community/GroupCarousel.jsx
> grp carousel kapeat näytöt

- frontend/src/components/content/movies/Reviews.jsx
- Ihan pieni tekstinhionta arvosteluissa; välilyönti paikalleen, kursiivina anon ja boldattuna user
> Arvosteluihin tekstinsäätö

- frontend/src/components/content/community/UserList.jsx
- frontend/src/components/content/community/community.css
- frontend/src/components/content/group/MemberList.jsx
- frontend/src/css/emoji.css
- frontend/src/css/styles.css
- frontend/src/css/theme.css
Jotain pientä huttua ja värejä, kontrastia niin ikään
> #160: vähän värejä ja muotoilua

- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/media.css
> Responsiivisuutta etusivuun ja hakutoimintoihin

- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
- backend/profile/profileService.js
- frontend/src/components/content/user/MyAccount.jsx
> Lisätty tilin hallintaan toggle k18

- backend/movie/movieService.js
- backend/profile/profileModel.js
- backend/profile/profileRoutes.js
- backend/profile/profileService.js
- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/user/MyAccount.jsx
> Hakutulosten sivunumero

- backend/profile/profileModel.js
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/header/Login.jsx
> tv-sarjoissa sydämestä voi lisätä ja poistaa favoriten omalle listalle

- backend/favoritelist/favoritelistRoutes.js
- backend/favoritelist/favoritelistService.js
- backend/profile/profileModel.js
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/header/Login.jsx
> Leffoissa sydämestä voi lisätä ja poistaa favoriten omalle listalle

- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/media.css
**Sijoitin nää sydämet h2 -otsikkotasolle syystä, että se osassa postereissa "hukkuu" kuvaan, kts.**
**Niin tää yleisesti toimii jotenki paremmin ja pysyy myös hyvin mukana koon muuttuessa:**
**Sekä sydän vähän kasvaa isommaksi hoverilla ja väri muuttuu hieman**
> #91: Heartzzzz

- frontend/src/components/content/user/MyAccount.jsx
- frontend/src/components/header/Login.jsx
- frontend/src/css/styles.css
Login sivun tyylejä muutettu ja poikkeuskäsittelyn viestien timeoutit lisätty
> #254 login messages

- backend/favoritelist/favoritelistRoutes.js
- backend/favoritelist/favoritelistService.js
- backend/movie/movieModel.js
- frontend/src/components/content/movies/movies.css
> Nyt ei pitäis arvostelun tehdessä välittyä oikein tuo adultstatus review_ tauluun

- frontend/src/components/content/user/FavoriteList.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- frontend/src/components/content/user/user.css
Valmis paketti 
-Suosikit näkyy
-Suosikin poisto onnistuu
-Muokkaa suosikkeja nappi lisätty jonka kautta poisto napit tulevat näkyviin posterin oikeaan ylälaitaan
-Muokattu näkymää 4suosikkia per sivu jotka näkyy näytöstä riippumatta aina 2rinnakkain myös puhelimella 
Tarpeen mukaan muokata nappia paremman näköseksi ja responsiivisuutta parantaa tarvittaessa.
> Käyttäjänsuosikit

- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
- Katsottu nyt suunillehen, että groupit ja profiilit toimii
-  edelleen jatkokehitykseen reviewListin kanssa juttuja:
ja myöskään esim. arvostelua ei pystynyt muokkaamaan!
> Fetching uzers

- backend/favoritelist/favoritelistService.js
- frontend/src/components/content/group/Forum.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/user/ReviewList.jsx
- Reviewlist (user-tasolta) korjattu
- eli arvostelujen muokkaus toimii taas
- Forum (group-tasolla) korjattu, nyt toimii viestien moderoinnit ja lähettämiset taas
- Grouppiin poistumisnappi paikalleen
- Endpointtiin fix;
- tässä oli if - else 404 ja tuli virhettä konsolille asti
- laitoin näin, koska ei ole virhe jos arvosteluja ei löyvy
> #87 #91 : reviewlist (from user) korjattu ja forum (from group)

- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
> Favoriitti lisäysnappi vain kirjautuneelle

- backend/movie/movieService.js
- backend/review/reviewModel.js
- frontend/src/components/content/community/AllReviews.jsx
- frontend/src/components/content/movies/Movies.jsx
- frontend/src/components/content/movies/movies.css
- frontend/src/css/media.css
- Anonyymit tulee jälleen etusivulle, mutta k18 tulokset suodatetaan pois:
- Konsolivirheitä saatu pois frontista mm. AllReviews
- K18 kilkettä korjattu, löytyi vikaa kun ei mennyt truena vaikka käyttäjällä oli sallittu materiaali
> #137 #230: anonyymit etusivulle ja k18 ja reviews fixes

- backend/favoritelist/favoritelistService.js
- frontend/src/components/content/group/FavoriteList.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
> suosikkilista ryhmään

- frontend/src/components/content/movies/Movies.jsx
- frontend/src/css/media.css
- suunnitelmat/Database-schema-group9.sql
> #15: Leffahaku: toolong titles ja hooverit, jotka levitti kuvia (mini ruudulla) fixed

- backend/favoritelist/favoritelistService.js
- frontend/src/App.jsx
- frontend/src/components/content/group/FavoriteList.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/user/FavoriteList.jsx
- frontend/src/components/content/user/Favorites.jsx
on se ruma mutta täyttää minimit
> Omasta profiilista näkee linkin jonka voi jakaa

- backend/favoritelist/favoritelistService.js
- frontend/src/components/content/group/FavoriteList.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/user/FavoriteList.jsx
> nyt on profiilin ja ryhmän suosikeissa blokki ettei ilman lupaa näy ronskit jutut

- frontend/src/components/content/user/FavoriteList.jsx
- frontend/src/components/content/user/ProfileDetails.jsx
> aivopieru korjattu

- frontend/src/components/content/group/MemberList.jsx
joo milläpä tätä voisi kuvilla demota :D kokeilkaa itse
> käyttäjähallinta ryhmässä nyt sulavampaa

- frontend/src/components/content/user/FavoriteList.jsx
> nappi suosikkien muokkaamiseen vain omassa profiilissa

- frontend/src/components/content/community/AllGroups.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/FavoriteList.jsx
- frontend/src/components/content/user/Favorites.jsx
- frontend/src/components/content/user/ReviewList.jsx
- frontend/src/components/content/user/user.css
- tarkastuksia hiottu, konsolivirheet poissa
- favoritelist profiileissa näkyviin julkisissa profiileissa
- öitä
> ProfileDetails + favorites + GroupDetails 

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/movies/ReviewFormSerie.jsx
peruuta muokkaus ei vielä palauta alkuun, mutta loppui aika kesken. tehkää tai jättäkää odottamaan
> review muokkaus

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/movies/ReviewFormSerie.jsx
> review muokkaus peruuta nappi lisätty

- backend/review/reviewModel.js
- backend/review/reviewRoutes.js
- backend/review/reviewService.js
- frontend/src/components/content/movies/ReviewForm.jsx
- frontend/src/components/content/movies/ReviewFormSerie.jsx
> Reviewedit nyt myös leffoissa

- frontend/src/components/content/group/Forum.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/group/GroupEdit.jsx
- sijoitin setAdminin vähän alemmas, nyt admin jos on ryhmän jäsen, pääsee ryhmätoimintoihin kuten kuuluu.
- alertit; ilmoitukset, varoitukset tulee käyttöliittymään, ei ponnahdusikkunoina
- admin pääsee kirjoittamaan viestejä 
- liittymispyynnön käsittely
> #163: GroupDetails: alertit, setAdmin sijainti, liittymispyyntökäsittely, Forum: admin moderointi

- frontend/src/components/content/group/GroupDetails.jsx
> ryhmästä poistumisen esto ainoana pääkäyttäjänä fix

- backend/test/test.js
> Lisätty testejä, nyt 10

- frontend/src/components/content/group/FavoriteList.jsx
- frontend/src/components/content/group/GroupDetails.jsx
- frontend/src/components/content/user/FavoriteList.jsx
> Suosikinpoisto nyt myös mainuserille ryhmässä

- frontend/src/components/content/admin/admins.css
- frontend/src/css/media.css
> Adminrespo

- frontend/src/components/content/group/GroupEvent.jsx
> näytösajoista pois thematti

- frontend/src/components/content/events/Events.jsx
- frontend/src/components/content/group/GroupEvent.jsx
- sql/database.sql
- sql/testdata.sql
- suunnitelmat/Database-schema-group9.sql
- Siivosin vähän konsolilokeja 
- Docker compose toimii taas, kun korjattu:
- testidata ja database skeema
> #296 : konsolilokit siivousta + lisäksi sql korjaus, Docker ok

- backend/favoritelist/favoritelistRoutes.js
- backend/favoritelist/favoritelistService.js
- backend/profile/profileModel.js
- frontend/src/components/content/group/FavoriteList.jsx
- frontend/src/components/content/movies/MovieDetails.jsx
- frontend/src/components/content/movies/SeriesDetails.jsx
- frontend/src/components/content/user/FavoriteList.jsx
Tällasia tänään, kaikki vaikuttais yhä toimivan kuten pitää
> Tarkistuksia
